// This runner is auto-generated by Brittle

runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await import('./basic.js')
  await import('./concurrent-writes.js')
  await import('./perf.js')
  await import('./optimistic-race.js')
  await import('./topo-sort.js')
  await import('./optimistic.js')

  test.resume()
}
