// This runner is auto-generated by Brittle

runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await import('./anchor-ordering.js')
  await import('./basic.js')
  await import('./catchable-boot.js')
  await import('./batch.js')
  await import('./close.js')
  await import('./concurrent-writes.js')
  await import('./conditional-grant.js')
  await import('./gated-grants.js')
  await import('./encryption.js')
  await import('./fast-forward.js')
  await import('./links.js')
  await import('./migration.js')
  await import('./optimistic-race.js')
  await import('./perf.js')
  await import('./updates.js')
  await import('./view-consistency.js')
  await import('./view-range.js')
  await import('./wakeup.js')
  await import('./wakeup-stall.js')
  await import('./wire-compat.js')
  await import('./witness.js')
  await import('./writer-management.js')

  test.resume()
}
