const LEGACY_OPLOG_VERSION = 2
const OPLOG_VERSION = 3
const LEGACY_AUTOBASE_VERSION = 2
const AUTOBEE_VERSION = 3

module.exports = {
  LEGACY_OPLOG_VERSION,
  OPLOG_VERSION,
  LEGACY_AUTOBASE_VERSION,
  AUTOBEE_VERSION
}
