// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @autobee/system-info
const encoding0 = {
  preencode(state, m) {
    encoding2.preencode(state, m.view)
    encoding0_1.preencode(state, m.heads)
  },
  encode(state, m) {
    encoding2.encode(state, m.view)
    encoding0_1.encode(state, m.heads)
  },
  decode(state) {
    const r0 = encoding2.decode(state)
    const r1 = encoding0_1.decode(state)

    return {
      view: r0,
      heads: r1
    }
  }
}

// @autobee/system-writer
const encoding1 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.key)
    c.uint.preencode(state, m.length)
    state.end++ // max flag is 4 so always one byte
  },
  encode(state, m) {
    const flags = (m.isIndexer ? 1 : 0) | (m.isRemoved ? 2 : 0) | (m.isOplog ? 4 : 0)

    c.fixed32.encode(state, m.key)
    c.uint.encode(state, m.length)
    c.uint.encode(state, flags)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const r1 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      length: r1,
      isIndexer: (flags & 1) !== 0,
      isRemoved: (flags & 2) !== 0,
      isOplog: (flags & 4) !== 0
    }
  }
}

// @autobee/link
const encoding2 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.key)
    c.uint.preencode(state, m.length)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.key)
    c.uint.encode(state, m.length)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const r1 = c.uint.decode(state)

    return {
      key: r0,
      length: r1
    }
  }
}

// @autobee/batch
const encoding3 = {
  preencode(state, m) {
    c.uint.preencode(state, m.start)
    c.uint.preencode(state, m.end)
  },
  encode(state, m) {
    c.uint.encode(state, m.start)
    c.uint.encode(state, m.end)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)

    return {
      start: r0,
      end: r1
    }
  }
}

// @autobee/oplog
const encoding4 = {
  preencode(state, m) {
    c.uint.preencode(state, m.version)
    c.uint.preencode(state, m.timestamp)
    encoding3.preencode(state, m.batch)
    encoding4_3.preencode(state, m.links)
    state.end++ // max flag is 2 so always one byte

    if (m.value) c.buffer.preencode(state, m.value)
  },
  encode(state, m) {
    const flags = (m.optimistic ? 1 : 0) | (m.value ? 2 : 0)

    c.uint.encode(state, m.version)
    c.uint.encode(state, m.timestamp)
    encoding3.encode(state, m.batch)
    encoding4_3.encode(state, m.links)
    c.uint.encode(state, flags)

    if (m.value) c.buffer.encode(state, m.value)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = encoding3.decode(state)
    const r3 = encoding4_3.decode(state)
    const flags = c.uint.decode(state)

    return {
      version: r0,
      timestamp: r1,
      batch: r2,
      links: r3,
      optimistic: (flags & 1) !== 0,
      value: (flags & 2) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @autobee/system-info.heads, deferred due to recusive use
const encoding0_1 = c.array(encoding2)
// @autobee/oplog.links, deferred due to recusive use
const encoding4_3 = encoding0_1

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@autobee/system-info':
      return encoding0
    case '@autobee/system-writer':
      return encoding1
    case '@autobee/link':
      return encoding2
    case '@autobee/batch':
      return encoding3
    case '@autobee/oplog':
      return encoding4
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
