// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @autobee/system-info
const encoding0 = {
  preencode(state, m) {
    encoding2.preencode(state, m.view)
    encoding0_1.preencode(state, m.heads)
    state.end++ // max flag is 1 so always one byte

    if (m.indexers) encoding0_2.preencode(state, m.indexers)
  },
  encode(state, m) {
    const flags = m.indexers ? 1 : 0

    encoding2.encode(state, m.view)
    encoding0_1.encode(state, m.heads)
    c.uint.encode(state, flags)

    if (m.indexers) encoding0_2.encode(state, m.indexers)
  },
  decode(state) {
    const r0 = encoding2.decode(state)
    const r1 = encoding0_1.decode(state)
    const flags = c.uint.decode(state)

    return {
      view: r0,
      heads: r1,
      indexers: (flags & 1) !== 0 ? encoding0_2.decode(state) : null
    }
  }
}

// @autobee/system-writer
const encoding1 = {
  preencode(state, m) {
    c.uint.preencode(state, m.length)
    state.end++ // max flag is 4 so always one byte
  },
  encode(state, m) {
    const flags = (m.isIndexer ? 1 : 0) | (m.isRemoved ? 2 : 0) | (m.isOplog ? 4 : 0)

    c.uint.encode(state, m.length)
    c.uint.encode(state, flags)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      length: r0,
      isIndexer: (flags & 1) !== 0,
      isRemoved: (flags & 2) !== 0,
      isOplog: (flags & 4) !== 0
    }
  }
}

// @autobee/link
const encoding2 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.key)
    c.uint.preencode(state, m.length)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.key)
    c.uint.encode(state, m.length)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const r1 = c.uint.decode(state)

    return {
      key: r0,
      length: r1
    }
  }
}

// @autobee/batch
const encoding3 = {
  preencode(state, m) {
    c.uint.preencode(state, m.start)
    c.uint.preencode(state, m.end)
  },
  encode(state, m) {
    c.uint.encode(state, m.start)
    c.uint.encode(state, m.end)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)

    return {
      start: r0,
      end: r1
    }
  }
}

// @autobee/views
const encoding4 = {
  preencode(state, m) {
    encoding2.preencode(state, m.system)
    state.end++ // flags are fixed size

    if (m.view) encoding2.preencode(state, m.view)
  },
  encode(state, m) {
    const flags = m.view ? 1 : 0

    encoding2.encode(state, m.system)
    c.uint8.encode(state, flags)

    if (m.view) encoding2.encode(state, m.view)
  },
  decode(state) {
    const r0 = encoding2.decode(state)
    const flags = c.uint8.decode(state)

    return {
      system: r0,
      view: (flags & 1) !== 0 ? encoding2.decode(state) : null
    }
  }
}

// @autobee/oplog
const encoding5 = {
  preencode(state, m) {
    c.uint.preencode(state, m.version)
    c.uint.preencode(state, m.timestamp)
    encoding3.preencode(state, m.batch)
    encoding5_3.preencode(state, m.links)
    state.end++ // max flag is 4 so always one byte

    if (m.views) encoding4.preencode(state, m.views)
    if (m.value) c.buffer.preencode(state, m.value)
  },
  encode(state, m) {
    const flags = (m.views ? 1 : 0) | (m.optimistic ? 2 : 0) | (m.value ? 4 : 0)

    c.uint.encode(state, m.version)
    c.uint.encode(state, m.timestamp)
    encoding3.encode(state, m.batch)
    encoding5_3.encode(state, m.links)
    c.uint.encode(state, flags)

    if (m.views) encoding4.encode(state, m.views)
    if (m.value) c.buffer.encode(state, m.value)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = encoding3.decode(state)
    const r3 = encoding5_3.decode(state)
    const flags = c.uint.decode(state)

    return {
      version: r0,
      timestamp: r1,
      batch: r2,
      links: r3,
      views: (flags & 1) !== 0 ? encoding4.decode(state) : null,
      optimistic: (flags & 2) !== 0,
      value: (flags & 4) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @autobee/system-info.heads, deferred due to recusive use
const encoding0_1 = c.array(encoding2)
// @autobee/system-info.indexers, deferred due to recusive use
const encoding0_2 = encoding0_1
// @autobee/oplog.links, deferred due to recusive use
const encoding5_3 = encoding0_1

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@autobee/system-info':
      return encoding0
    case '@autobee/system-writer':
      return encoding1
    case '@autobee/link':
      return encoding2
    case '@autobee/batch':
      return encoding3
    case '@autobee/views':
      return encoding4
    case '@autobee/oplog':
      return encoding5
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
