// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @autobee/system-info
const encoding0 = {
  preencode(state, m) {
    c.uint.preencode(state, m.version)
    c.uint.preencode(state, m.timestamp)
    c.uint.preencode(state, m.flushes)
    encoding2.preencode(state, m.view)
    encoding0_4.preencode(state, m.heads)
    state.end++ // max flag is 1 so always one byte

    if (m.indexers) encoding0_5.preencode(state, m.indexers)
  },
  encode(state, m) {
    const flags = m.indexers ? 1 : 0

    c.uint.encode(state, m.version)
    c.uint.encode(state, m.timestamp)
    c.uint.encode(state, m.flushes)
    encoding2.encode(state, m.view)
    encoding0_4.encode(state, m.heads)
    c.uint.encode(state, flags)

    if (m.indexers) encoding0_5.encode(state, m.indexers)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = encoding2.decode(state)
    const r4 = encoding0_4.decode(state)
    const flags = c.uint.decode(state)

    return {
      version: r0,
      timestamp: r1,
      flushes: r2,
      view: r3,
      heads: r4,
      indexers: (flags & 1) !== 0 ? encoding0_5.decode(state) : null
    }
  }
}

// @autobee/system-writer
const encoding1 = {
  preencode(state, m) {
    c.uint.preencode(state, m.length)
    state.end++ // max flag is 4 so always one byte
  },
  encode(state, m) {
    const flags = (m.isIndexer ? 1 : 0) | (m.isRemoved ? 2 : 0) | (m.isOplog ? 4 : 0)

    c.uint.encode(state, m.length)
    c.uint.encode(state, flags)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      length: r0,
      isIndexer: (flags & 1) !== 0,
      isRemoved: (flags & 2) !== 0,
      isOplog: (flags & 4) !== 0
    }
  }
}

// @autobee/link
const encoding2 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.key)
    c.uint.preencode(state, m.length)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.key)
    c.uint.encode(state, m.length)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const r1 = c.uint.decode(state)

    return {
      key: r0,
      length: r1
    }
  }
}

// @autobee/batch
const encoding3 = {
  preencode(state, m) {
    c.uint.preencode(state, m.start)
    c.uint.preencode(state, m.end)
  },
  encode(state, m) {
    c.uint.encode(state, m.start)
    c.uint.encode(state, m.end)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)

    return {
      start: r0,
      end: r1
    }
  }
}

// @autobee/views
const encoding4 = {
  preencode(state, m) {
    encoding2.preencode(state, m.system)
    c.uint.preencode(state, m.flushes)
    state.end++ // flags are fixed size

    if (m.view) encoding2.preencode(state, m.view)
  },
  encode(state, m) {
    const flags = m.view ? 1 : 0

    encoding2.encode(state, m.system)
    c.uint.encode(state, m.flushes)
    c.uint8.encode(state, flags)

    if (m.view) encoding2.encode(state, m.view)
  },
  decode(state) {
    const r0 = encoding2.decode(state)
    const r1 = c.uint.decode(state)
    const flags = c.uint8.decode(state)

    return {
      system: r0,
      flushes: r1,
      view: (flags & 1) !== 0 ? encoding2.decode(state) : null
    }
  }
}

// @autobee/views (inline)
const encoding4_inline = {
  preencode(state, m) {
    encoding2.preencode(state, m.system)
    c.uint.preencode(state, m.flushes)

    if (m.view) encoding2.preencode(state, m.view)
  },
  encode(state, m) {
    encoding2.encode(state, m.system)
    c.uint.encode(state, m.flushes)

    if (m.view) encoding2.encode(state, m.view)
  },
  decode(state, inlining) {
    const r0 = encoding2.decode(state)
    const r1 = c.uint.decode(state)
    const flags = inlining

    return {
      system: r0,
      flushes: r1,
      view: (flags & 1) !== 0 ? encoding2.decode(state) : null
    }
  }
}

// @autobee/oplog-message-v0
const encoding5 = {
  preencode(state, m) {
    c.uint.preencode(state, m.timestamp)
    encoding5_1.preencode(state, m.links)
    state.end++ // max flag is 16 so always one byte

    if (m.batch) encoding3.preencode(state, m.batch)
    if (m.views) encoding4_inline.preencode(state, m.views)
    if (m.value) c.buffer.preencode(state, m.value)
  },
  encode(state, m) {
    let flags = (m.batch ? 1 : 0) | (m.views ? 2 : 0) | (m.optimistic ? 8 : 0) | (m.value ? 16 : 0)
    if (m.views) {
      flags |= m.views.view ? 4 : 0
    }

    c.uint.encode(state, m.timestamp)
    encoding5_1.encode(state, m.links)
    c.uint.encode(state, flags)

    if (m.batch) encoding3.encode(state, m.batch)
    if (m.views) encoding4_inline.encode(state, m.views)
    if (m.value) c.buffer.encode(state, m.value)
  },
  decode(state) {
    const v = c.uint.decode(state)
    const r0 = c.uint.decode(state)
    const r1 = encoding5_1.decode(state)
    const flags = c.uint.decode(state)

    return {
      version: v,
      timestamp: r0,
      links: r1,
      batch: (flags & 1) !== 0 ? encoding3.decode(state) : null,
      views: (flags & 2) !== 0 ? encoding4_inline.decode(state, flags >>> 2) : null,
      optimistic: (flags & 8) !== 0,
      value: (flags & 16) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @autobase-compat/checkout
const encoding6 = encoding2

// @autobase-compat/clock
const encoding7 = c.array(encoding6)

// @autobase-compat/index-checkpoint
const encoding8 = {
  preencode(state, m) {
    c.fixed64.preencode(state, m.signature)
    c.uint.preencode(state, m.length)
  },
  encode(state, m) {
    c.fixed64.encode(state, m.signature)
    c.uint.encode(state, m.length)
  },
  decode(state) {
    const r0 = c.fixed64.decode(state)
    const r1 = c.uint.decode(state)

    return {
      signature: r0,
      length: r1
    }
  }
}

// @autobase-compat/checkpointer
const encoding9 = {
  preencode(state, m) {
    state.end++ // flags are fixed size

    if (m.checkpointer) c.uint.preencode(state, m.checkpointer)
    if (m.checkpoint) encoding8.preencode(state, m.checkpoint)
  },
  encode(state, m) {
    const flags = (m.checkpointer ? 1 : 0) | (m.checkpoint ? 2 : 0)

    c.uint8.encode(state, flags)

    if (m.checkpointer) c.uint.encode(state, m.checkpointer)
    if (m.checkpoint) encoding8.encode(state, m.checkpoint)
  },
  decode(state) {
    const flags = c.uint8.decode(state)

    return {
      checkpointer: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      checkpoint: (flags & 2) !== 0 ? encoding8.decode(state) : null
    }
  }
}

// @autobase-compat/checkpoint.user
const encoding10_2 = c.array(encoding9)

// @autobase-compat/checkpoint
const encoding10 = {
  preencode(state, m) {
    state.end++ // max flag is 4 so always one byte

    if (m.system) encoding9.preencode(state, m.system)
    if (m.encryption) encoding9.preencode(state, m.encryption)
    if (m.user) encoding10_2.preencode(state, m.user)
  },
  encode(state, m) {
    const flags = (m.system ? 1 : 0) | (m.encryption ? 2 : 0) | (m.user ? 4 : 0)

    c.uint.encode(state, flags)

    if (m.system) encoding9.encode(state, m.system)
    if (m.encryption) encoding9.encode(state, m.encryption)
    if (m.user) encoding10_2.encode(state, m.user)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      system: (flags & 1) !== 0 ? encoding9.decode(state) : null,
      encryption: (flags & 2) !== 0 ? encoding9.decode(state) : null,
      user: (flags & 4) !== 0 ? encoding10_2.decode(state) : null
    }
  }
}

// @autobase-compat/digest
const encoding11 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.pointer) c.uint.preencode(state, m.pointer)
    if (m.key) c.fixed32.preencode(state, m.key)
  },
  encode(state, m) {
    const flags = (m.pointer ? 1 : 0) | (m.key ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.pointer) c.uint.encode(state, m.pointer)
    if (m.key) c.fixed32.encode(state, m.key)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      pointer: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      key: (flags & 2) !== 0 ? c.fixed32.decode(state) : null
    }
  }
}

// @autobase-compat/node
const encoding12 = {
  preencode(state, m) {
    encoding7.preencode(state, m.heads)
    c.uint.preencode(state, m.batch)
    c.buffer.preencode(state, m.value)
  },
  encode(state, m) {
    encoding7.encode(state, m.heads)
    c.uint.encode(state, m.batch)
    c.buffer.encode(state, m.value)
  },
  decode(state) {
    const r0 = encoding7.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.buffer.decode(state)

    return {
      heads: r0,
      batch: r1,
      value: r2
    }
  }
}

// @autobase-compat/user-view-trace.blocks
const encoding13_1 = c.array(c.uint)

// @autobase-compat/user-view-trace
const encoding13 = {
  preencode(state, m) {
    c.uint.preencode(state, m.view)
    encoding13_1.preencode(state, m.blocks)
  },
  encode(state, m) {
    c.uint.encode(state, m.view)
    encoding13_1.encode(state, m.blocks)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = encoding13_1.decode(state)

    return {
      view: r0,
      blocks: r1
    }
  }
}

// @autobase-compat/trace.system
const encoding14_0 = encoding13_1
// @autobase-compat/trace.encryption
const encoding14_1 = encoding13_1
// @autobase-compat/trace.user
const encoding14_2 = c.array(encoding13)

// @autobase-compat/trace
const encoding14 = {
  preencode(state, m) {
    encoding14_0.preencode(state, m.system)
    encoding14_1.preencode(state, m.encryption)
    encoding14_2.preencode(state, m.user)
  },
  encode(state, m) {
    encoding14_0.encode(state, m.system)
    encoding14_1.encode(state, m.encryption)
    encoding14_2.encode(state, m.user)
  },
  decode(state) {
    const r0 = encoding14_0.decode(state)
    const r1 = encoding14_1.decode(state)
    const r2 = encoding14_2.decode(state)

    return {
      system: r0,
      encryption: r1,
      user: r2
    }
  }
}

// @autobase-compat/oplog-message-v2.checkpoint
const encoding15_1 = c.frame(encoding10)
// @autobase-compat/oplog-message-v2.digest
const encoding15_2 = c.frame(encoding11)
// @autobase-compat/oplog-message-v2.trace
const encoding15_4 = c.frame(encoding14)

// @autobase-compat/oplog-message-v2
const encoding15 = {
  preencode(state, m) {
    encoding12.preencode(state, m.node)
    state.end++ // max flag is 8 so always one byte

    if (m.checkpoint) encoding15_1.preencode(state, m.checkpoint)
    if (m.digest) encoding15_2.preencode(state, m.digest)
    if (m.trace) encoding15_4.preencode(state, m.trace)
  },
  encode(state, m) {
    const flags =
      (m.checkpoint ? 1 : 0) | (m.digest ? 2 : 0) | (m.optimistic ? 4 : 0) | (m.trace ? 8 : 0)

    encoding12.encode(state, m.node)
    c.uint.encode(state, flags)

    if (m.checkpoint) encoding15_1.encode(state, m.checkpoint)
    if (m.digest) encoding15_2.encode(state, m.digest)
    if (m.trace) encoding15_4.encode(state, m.trace)
  },
  decode(state) {
    const v = c.uint.decode(state)
    const r0 = encoding12.decode(state)
    const flags = c.uint.decode(state)

    return {
      version: v,
      node: r0,
      checkpoint: (flags & 1) !== 0 ? encoding15_1.decode(state) : null,
      digest: (flags & 2) !== 0 ? encoding15_2.decode(state) : null,
      optimistic: (flags & 4) !== 0,
      trace: (flags & 8) !== 0 ? encoding15_4.decode(state) : null
    }
  }
}

// @autobee/oplog
const encoding16 = {
  preencode(state, m) {
    c.uint.preencode(state, m.version)
    switch (m.version) {
      case 0:
      case 1:
      case 2:
        encoding15.preencode(state, m)
        break
      case 3:
      case 4:
        encoding5.preencode(state, m)
        break
      default:
        throw new Error('Unsupported version')
    }
  },
  encode(state, m) {
    c.uint.encode(state, m.version)
    switch (m.version) {
      case 0:
      case 1:
      case 2:
        encoding15.encode(state, m)
        break
      case 3:
      case 4:
        encoding5.encode(state, m)
        break
      default:
        throw new Error('Unsupported version')
    }
  },
  decode(state) {
    const start = state.start
    const v = c.uint.decode(state)
    state.start = start
    switch (v) {
      case 0:
      case 1:
      case 2: {
        const decoded = encoding15.decode(state)
        return decoded
      }
      case 3:
      case 4: {
        const decoded = encoding5.decode(state)
        return decoded
      }
      default:
        throw new Error('Unsupported version')
    }
  }
}

// @autobee/system-info.heads, deferred due to recusive use
const encoding0_4 = c.array(encoding2)
// @autobee/system-info.indexers, deferred due to recusive use
const encoding0_5 = encoding0_4
// @autobee/oplog-message-v0.links, deferred due to recusive use
const encoding5_1 = encoding0_4

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@autobee/system-info':
      return encoding0
    case '@autobee/system-writer':
      return encoding1
    case '@autobee/link':
      return encoding2
    case '@autobee/batch':
      return encoding3
    case '@autobee/views':
      return encoding4
    case '@autobee/oplog-message-v0':
      return encoding5
    case '@autobase-compat/checkout':
      return encoding6
    case '@autobase-compat/clock':
      return encoding7
    case '@autobase-compat/index-checkpoint':
      return encoding8
    case '@autobase-compat/checkpointer':
      return encoding9
    case '@autobase-compat/checkpoint':
      return encoding10
    case '@autobase-compat/digest':
      return encoding11
    case '@autobase-compat/node':
      return encoding12
    case '@autobase-compat/user-view-trace':
      return encoding13
    case '@autobase-compat/trace':
      return encoding14
    case '@autobase-compat/oplog-message-v2':
      return encoding15
    case '@autobee/oplog':
      return encoding16
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
